INSERT INTO EMPLOYE (ID_EMPLOYE, NOM, PRENOM, SALAIRE, AGE, DIPLOME)  VALUES (1, 'GACONT', 'JOFRE', 1500, 20, 'DIPLOME COOL');
INSERT INTO EMPLOYE (ID_EMPLOYE, NOM, PRENOM, SALAIRE, AGE, DIPLOME)  VALUES (2, 'GIGOUX', 'JOKAN', 1600, 25, 'DIPLOME NUL');
INSERT INTO EMPLOYE (ID_EMPLOYE, NOM, PRENOM, SALAIRE, AGE, DIPLOME)  VALUES (3, 'MARKIN', 'LEOX', 2100, 43, 'DIPLOME TROP FORT');
INSERT INTO EMPLOYE (ID_EMPLOYE, NOM, PRENOM, SALAIRE, AGE, DIPLOME)  VALUES (4, 'HRV', 'BASTOF', 2500, 21, 'DIPLOME DE BAST');
INSERT INTO EMPLOYE (ID_EMPLOYE, NOM, PRENOM, SALAIRE, AGE, DIPLOME)  VALUES (5, 'GALLANTUX', 'TOMA', 4000, 36, 'DIPLOME DE FOU');
INSERT INTO EMPLOYE (ID_EMPLOYE, NOM, PRENOM, SALAIRE, AGE, DIPLOME)  VALUES (6, 'LOURSSE', 'MATHILDUX', 1200, 24, 'DIPLOME DE CUISINIER');
INSERT INTO EMPLOYE (ID_EMPLOYE, NOM, PRENOM, SALAIRE, AGE, DIPLOME)  VALUES (7, 'FERANDUX', 'ANUX', '3200', '41', 'ARCHITEC');
INSERT INTO EMPLOYE (ID_EMPLOYE, NOM, PRENOM, SALAIRE, AGE, DIPLOME)  VALUES (8, 'KIKOO', 'KPOP', '1300', '18', 'BIOLOGIE ');
INSERT INTO EMPLOYE (ID_EMPLOYE, NOM, PRENOM, SALAIRE, AGE, DIPLOME)  VALUES (9, 'BOUSQ', 'ZOEYOUX', '3100', '23', 'ANTHROPO');
INSERT INTO EMPLOYE (ID_EMPLOYE, NOM, PRENOM, SALAIRE, AGE, DIPLOME)  VALUES (10, 'PETITE', 'ARIANA', '8000', '22', 'CHANTEUR');

INSERT INTO CLIENT (ID_CLIENT,NOM,PRENOM,AGE) VALUES (1,'GROS','CHARLES','18');
INSERT INTO CLIENT (ID_CLIENT,NOM,PRENOM,AGE) VALUES (2,'MAIRGRE','JEAN','25');

INSERT INTO VENTE (ID_EMPLOYE,ID_MARCH,ID_CLIENT,PRESCRIPTION,DATE_VENTE) VALUES (3,1,


INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (1,'LUNDI',1);
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    2  , 'MARDI' ,1 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    3  , 'MERCREDI' ,1 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    4  , 'JEUDI' ,1 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    5  , 'VENDREDI' ,1 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    6  , 'SAMEDI',1 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    7  , 'LUNDI',2 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    8  , 'MARDI' ,2 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    9  , 'MERCREDI' ,2 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    10  , 'JEUDI' ,2 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    11  , 'VENDREDI' ,2 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    12  , 'SAMEDI' ,2 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    13  , 'LUNDI' ,3 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    14  , 'MARDI',3 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    15  , 'MERCREDI',3 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    16  , 'JEUDI' ,3 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    17  , 'VENDREDI' ,3 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    18  , 'SAMEDI' ,3 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    19  , 'LUNDI' ,4 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    20  , 'MARDI' ,4 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    21  , 'MERCREDI' ,4 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    22  , 'JEUDI' ,4 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    23  , 'VENDREDI' ,4 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    24  , 'SAMEDI' ,4 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    25  , 'LUNDI' ,5 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    26  , 'MARDI' ,5 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    27  , 'MERCREDI' ,5 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    28  , 'JEUDI' ,5 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    29  , 'VENDREDI' ,5 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    30  , 'SAMEDI' ,5 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    31  , 'LUNDI' ,6 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    32  , 'MARDI' ,6 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    33  , 'MERCREDI' ,6 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    34  , 'JEUDI' ,6 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    35  , 'VENDREDI' ,6 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    36  , 'SAMEDI' ,6 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    37  , 'LUNDI' ,7 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    38  , 'MARDI' ,7 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    39  , 'MERCREDI' ,7 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    40  , 'JEUDI' ,7 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    41  , 'VENDREDI' ,7 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    42  , 'SAMEDI' ,7 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    43  , 'LUNDI' ,8 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    44  , 'MARDI' ,8 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    45  , 'MERCREDI' ,8 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    46  , 'JEUDI' ,8 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    47  , 'VENDREDI' ,8 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    48  , 'SAMEDI' ,8 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    49  , 'LUNDI' ,9 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    50  , 'MARDI' ,9 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    51  , 'MERCREDI' ,9 );
INSERT INTO HORAIRE (ID_HORAIRE, JOUR_SEMAINE, NUMERO_SEMAINE)VALUES (    52  , 'JEUDI' ,9 );

INSERT INTO PRODUIT (ID_PRODUIT,NOM_MARCH,PRIX,PRESCRIPTION,TAUX_REMBOURSEMENT,DESCRIPTION,QUANTITE) VALUES (1,'DOLIPRANE',6,0,0,'est un antalgique (calme la douleur) et un antipyrétique (fait baisser la fièvre). La substance active de ce médicament est le paracétamol.',600);
INSERT INTO PRODUIT (ID_PRODUIT,NOM_MARCH,PRIX,PRESCRIPTION,TAUX_REMBOURSEMENT,DESCRIPTION,QUANTITE) VALUES (2,'DAFALGAN',5.5,0,'est un antalgique (calme la douleur) et un antipyrétique (fait baisser la fièvre). La substance active de ce médicament est le paracétamol.',700);
INSERT INTO PRODUIT (ID_PRODUIT,NOM_MARCH,PRIX,PRESCRIPTION,TAUX_REMBOURSEMENT,DESCRIPTION,QUANTITE) VALUES (3,'EFFERALGAN',7,0,'est un antalgique (calme la douleur) et un antipyrétique (fait baisser la fièvre). La substance active de ce médicament est le paracétamol.',200);
INSERT INTO PRODUIT (ID_PRODUIT,NOM_MARCH,PRIX,PRESCRIPTION,TAUX_REMBOURSEMENT,DESCRIPTION,QUANTITE) VALUES (4,'TRUCMUCHE',20,50,'est une pommade anti-inflammatoire',59);
INSERT INTO PRODUIT (ID_PRODUIT,NOM_MARCH,PRIX,PRESCRIPTION,TAUX_REMBOURSEMENT,DESCRIPTION,QUANTITE) VALUES (5,'SUPER PILLULE',100,0,'est une super pillule qui double votre force',103);
INSERT INTO PRODUIT (ID_PRODUIT,NOM_MARCH,PRIX,PRESCRIPTION,TAUX_REMBOURSEMENT,DESCRIPTION,QUANTITE) VALUES (6,'PILLULE GROSSISANTE',30,25,'est une pillule qui fait grossir',556);
INSERT INTO PRODUIT (ID_PRODUIT,NOM_MARCH,PRIX,PRESCRIPTION,TAUX_REMBOURSEMENT,DESCRIPTION,QUANTITE) VALUES (7,'PROTOX',15,100,'une boisson qui vous rend heureux',1200);
INSERT INTO PRODUIT (ID_PRODUIT,NOM_MARCH,PRIX,PRESCRIPTION,TAUX_REMBOURSEMENT,DESCRIPTION,QUANTITE) VALUES (8,'SADTRISTEFOU',6,75,'est un produit effervescent qui vous rends triste',666);
INSERT INTO PRODUIT (ID_PRODUIT,NOM_MARCH,PRIX,PRESCRIPTION,TAUX_REMBOURSEMENT,DESCRIPTION,QUANTITE) VALUES (9,'MAIRGRE-TOUT-DE-SUITE',234,25,'vous fait maigrir en deux nuits',23);
INSERT INTO PRODUIT (ID_PRODUIT,NOM_MARCH,PRIX,PRESCRIPTION,TAUX_REMBOURSEMENT,DESCRIPTION,QUANTITE) VALUES (10,'SUPPFESE',16,0,'est un suppositoire qui vous guéri de la covid-19',254);






INSERT INTO TRAVAILLE (ID_EMPLOYE, ID_HORAIRE) VALUES (1,1);
INSERT INTO TRAVAILLE (ID_EMPLOYE, ID_HORAIRE) VALUES (1, 2);
INSERT INTO TRAVAILLE (ID_EMPLOYE, ID_HORAIRE) VALUES (1, 3);

