INSERT INTO `EMPLOYE` (`ID_EMPLOYE`, `NOM`, `PRENOM`, `SALAIRE`, `AGE`, `DIPLOME`)
VALUES (NULL, 'GACONT', 'JOFRE', '1500', '20', 'DIPLOME COOL'),
       (NULL, 'GIGOUX', 'JOKAN', '1600', '25', 'DIPLOME NUL'),
       (NULL, 'MARKIN', 'LEOX', '2100', '43', 'DIPLOME TROP FORT'),
       (NULL, 'HRV', 'BASTOF', '2500', '21', 'DIPLOME DE BAST'),
       (NULL, 'GALLANTUX', 'TOMA', '4000', '36', 'DIPLOME DE FOU'),
       (NULL, 'LOURSSE', 'MATHILDUX', '1200', '24', 'DIPLOME DE CUISINIER'),
       (NULL, 'FERANDUX', 'ANUX', '3200', '41', 'ARCHITEC'),
       (NULL, 'KIKOO', 'KPOP', '1300', '18', 'BIOLOGIE '),
       (NULL, 'BOUSQ', 'ZOEYOUX', '3100', '23', 'ANTHROPO'),
       (NULL, 'PETITE', 'ARIANA', '8000', '22', 'CHANTEUR');






INSERT INTO `HORAIRE` (`ID_HORAIRE`, `JOUR_SEMAINE`, `NUMERO_SEMAINE`)
VALUES (NULL, 'LUNDI', '1'), (NULL, 'MARDI', '1'), (NULL, 'MERCREDI', '1'),
       (NULL, 'JEUDI', '1'), (NULL, 'VENDREDI', '1'), (NULL, 'SAMEDI', '1'),
       (NULL, 'LUNDI', '2'), (NULL, 'MARDI', '2'), (NULL, 'MERCREDI', '2'),
       (NULL, 'JEUDI', '2'), (NULL, 'VENDREDI', '2'), (NULL, 'SAMEDI', '2'),
       (NULL, 'LUNDI', '3'), (NULL, 'MARDI', '3'), (NULL, 'MERCREDI', '3'),
       (NULL, 'JEUDI', '3'), (NULL, 'VENDREDI', '3'), (NULL, 'SAMEDI', '3'),
       (NULL, 'LUNDI', '4'), (NULL, 'MARDI', '4'), (NULL, 'MERCREDI', '4'),
       (NULL, 'JEUDI', '4'), (NULL, 'VENDREDI', '4'), (NULL, 'SAMEDI', '4'),
       (NULL, 'LUNDI', '5'), (NULL, 'MARDI', '5'), (NULL, 'MERCREDI', '5'),
       (NULL, 'JEUDI', '5'), (NULL, 'VENDREDI', '5'), (NULL, 'SAMEDI', '5'),
       (NULL, 'LUNDI', '6'), (NULL, 'MARDI', '6'), (NULL, 'MERCREDI', '6'),
       (NULL, 'JEUDI', '6'), (NULL, 'VENDREDI', '6'), (NULL, 'SAMEDI', '6'),
       (NULL, 'LUNDI', '7'), (NULL, 'MARDI', '7'), (NULL, 'MERCREDI', '7'),
       (NULL, 'JEUDI', '7'), (NULL, 'VENDREDI', '7'), (NULL, 'SAMEDI', '7'),
       (NULL, 'LUNDI', '8'), (NULL, 'MARDI', '8'), (NULL, 'MERCREDI', '8'),
       (NULL, 'JEUDI', '8'), (NULL, 'VENDREDI', '8'), (NULL, 'SAMEDI', '8'),
       (NULL, 'LUNDI', '9'), (NULL, 'MARDI', '9'), (NULL, 'MERCREDI', '9'),
       (NULL, 'JEUDI', '9'), (NULL, 'VENDREDI', '9'), (NULL, 'SAMEDI', '9'),
       (NULL, 'LUNDI', '10'), (NULL, 'MARDI', '10'), (NULL, 'MERCREDI', '10'),
       (NULL, 'JEUDI', '10'), (NULL, 'VENDREDI', '10'), (NULL, 'SAMEDI', '10'),
       (NULL, 'LUNDI', '11'), (NULL, 'MARDI', '11'), (NULL, 'MERCREDI', '11'),
       (NULL, 'JEUDI', '11'), (NULL, 'VENDREDI', '11'), (NULL, 'SAMEDI', '11'),
       (NULL, 'LUNDI', '12'), (NULL, 'MARDI', '12'), (NULL, 'MERCREDI', '12'),
       (NULL, 'JEUDI', '12'), (NULL, 'VENDREDI', '12'), (NULL, 'SAMEDI', '12'),
       (NULL, 'LUNDI', '13'), (NULL, 'MARDI', '13'), (NULL, 'MERCREDI', '13'),
       (NULL, 'JEUDI', '13'), (NULL, 'VENDREDI', '13'), (NULL, 'SAMEDI', '13'),
       (NULL, 'LUNDI', '14'), (NULL, 'MARDI', '14'), (NULL, 'MERCREDI', '14'),
       (NULL, 'JEUDI', '14'), (NULL, 'VENDREDI', '14'), (NULL, 'SAMEDI', '14'),
       (NULL, 'LUNDI', '15'), (NULL, 'MARDI', '15'), (NULL, 'MERCREDI', '15'),
       (NULL, 'JEUDI', '15'), (NULL, 'VENDREDI', '15'), (NULL, 'SAMEDI', '15'),
       (NULL, 'LUNDI', '16'), (NULL, 'MARDI', '16'), (NULL, 'MERCREDI', '16'),
       (NULL, 'JEUDI', '16'), (NULL, 'VENDREDI', '16'), (NULL, 'SAMEDI', '16'),
       (NULL, 'LUNDI', '17'), (NULL, 'MARDI', '17'), (NULL, 'MERCREDI', '17'),
       (NULL, 'JEUDI', '17'), (NULL, 'VENDREDI', '17'), (NULL, 'SAMEDI', '17'),
       (NULL, 'LUNDI', '18'), (NULL, 'MARDI', '18'), (NULL, 'MERCREDI', '18'),
       (NULL, 'JEUDI', '18'), (NULL, 'VENDREDI', '18'), (NULL, 'SAMEDI', '18'),
       (NULL, 'LUNDI', '19'), (NULL, 'MARDI', '19'), (NULL, 'MERCREDI', '19'),
       (NULL, 'JEUDI', '19'), (NULL, 'VENDREDI', '19'), (NULL, 'SAMEDI', '19'),
       (NULL, 'LUNDI', '20'), (NULL, 'MARDI', '20'), (NULL, 'MERCREDI', '20'),
       (NULL, 'JEUDI', '20'), (NULL, 'VENDREDI', '20'), (NULL, 'SAMEDI', '20'),
       (NULL, 'LUNDI', '21'), (NULL, 'MARDI', '21'), (NULL, 'MERCREDI', '21'),
       (NULL, 'JEUDI', '21'), (NULL, 'VENDREDI', '21'), (NULL, 'SAMEDI', '21'),
       (NULL, 'LUNDI', '22'), (NULL, 'MARDI', '22'), (NULL, 'MERCREDI', '22'),
       (NULL, 'JEUDI', '22'), (NULL, 'VENDREDI', '22'), (NULL, 'SAMEDI', '22'),
       (NULL, 'LUNDI', '23'), (NULL, 'MARDI', '23'), (NULL, 'MERCREDI', '23'),
       (NULL, 'JEUDI', '23'), (NULL, 'VENDREDI', '23'), (NULL, 'SAMEDI', '23'),
       (NULL, 'LUNDI', '24'), (NULL, 'MARDI', '24'), (NULL, 'MERCREDI', '24'),
       (NULL, 'JEUDI', '24'), (NULL, 'VENDREDI', '24'), (NULL, 'SAMEDI', '24'),
       (NULL, 'LUNDI', '25'), (NULL, 'MARDI', '25'), (NULL, 'MERCREDI', '25'),
       (NULL, 'JEUDI', '25'), (NULL, 'VENDREDI', '25'), (NULL, 'SAMEDI', '25'),
       (NULL, 'LUNDI', '26'), (NULL, 'MARDI', '26'), (NULL, 'MERCREDI', '26'),
       (NULL, 'JEUDI', '26'), (NULL, 'VENDREDI', '26'), (NULL, 'SAMEDI', '26'),
       (NULL, 'LUNDI', '27'), (NULL, 'MARDI', '27'), (NULL, 'MERCREDI', '27'),
       (NULL, 'JEUDI', '27'), (NULL, 'VENDREDI', '27'), (NULL, 'SAMEDI', '27'),
       (NULL, 'LUNDI', '28'), (NULL, 'MARDI', '28'), (NULL, 'MERCREDI', '28'),
       (NULL, 'JEUDI', '28'), (NULL, 'VENDREDI', '28'), (NULL, 'SAMEDI', '28'),
       (NULL, 'LUNDI', '29'), (NULL, 'MARDI', '29'), (NULL, 'MERCREDI', '29'),
       (NULL, 'JEUDI', '29'), (NULL, 'VENDREDI', '29'), (NULL, 'SAMEDI', '29'),
       (NULL, 'LUNDI', '30'), (NULL, 'MARDI', '30'), (NULL, 'MERCREDI', '30'),
       (NULL, 'JEUDI', '30'), (NULL, 'VENDREDI', '30'), (NULL, 'SAMEDI', '30'),
       (NULL, 'LUNDI', '31'), (NULL, 'MARDI', '31'), (NULL, 'MERCREDI', '31'),
       (NULL, 'JEUDI', '31'), (NULL, 'VENDREDI', '31'), (NULL, 'SAMEDI', '31'),
       (NULL, 'LUNDI', '32'), (NULL, 'MARDI', '32'), (NULL, 'MERCREDI', '32'),
       (NULL, 'JEUDI', '32'), (NULL, 'VENDREDI', '32'), (NULL, 'SAMEDI', '32'),
       (NULL, 'LUNDI', '33'), (NULL, 'MARDI', '33'), (NULL, 'MERCREDI', '33'),
       (NULL, 'JEUDI', '33'), (NULL, 'VENDREDI', '33'), (NULL, 'SAMEDI', '33'),
       (NULL, 'LUNDI', '34'), (NULL, 'MARDI', '34'), (NULL, 'MERCREDI', '34'),
       (NULL, 'JEUDI', '34'), (NULL, 'VENDREDI', '34'), (NULL, 'SAMEDI', '34'),
       (NULL, 'LUNDI', '35'), (NULL, 'MARDI', '35'), (NULL, 'MERCREDI', '35'),
       (NULL, 'JEUDI', '35'), (NULL, 'VENDREDI', '35'), (NULL, 'SAMEDI', '35'),
       (NULL, 'LUNDI', '36'), (NULL, 'MARDI', '36'), (NULL, 'MERCREDI', '36'),
       (NULL, 'JEUDI', '36'), (NULL, 'VENDREDI', '36'), (NULL, 'SAMEDI', '36'),
       (NULL, 'LUNDI', '37'), (NULL, 'MARDI', '37'), (NULL, 'MERCREDI', '37'),
       (NULL, 'JEUDI', '37'), (NULL, 'VENDREDI', '37'), (NULL, 'SAMEDI', '37'),
       (NULL, 'LUNDI', '38'), (NULL, 'MARDI', '38'), (NULL, 'MERCREDI', '38'),
       (NULL, 'JEUDI', '38'), (NULL, 'VENDREDI', '38'), (NULL, 'SAMEDI', '38'),
       (NULL, 'LUNDI', '39'), (NULL, 'MARDI', '39'), (NULL, 'MERCREDI', '39'),
       (NULL, 'JEUDI', '39'), (NULL, 'VENDREDI', '39'), (NULL, 'SAMEDI', '39'),
       (NULL, 'LUNDI', '40'), (NULL, 'MARDI', '40'), (NULL, 'MERCREDI', '40'),
       (NULL, 'JEUDI', '40'), (NULL, 'VENDREDI', '40'), (NULL, 'SAMEDI', '40'),
       (NULL, 'LUNDI', '41'), (NULL, 'MARDI', '41'), (NULL, 'MERCREDI', '41'),
       (NULL, 'JEUDI', '41'), (NULL, 'VENDREDI', '41'), (NULL, 'SAMEDI', '41'),
       (NULL, 'LUNDI', '42'), (NULL, 'MARDI', '42'), (NULL, 'MERCREDI', '42'),
       (NULL, 'JEUDI', '42'), (NULL, 'VENDREDI', '42'), (NULL, 'SAMEDI', '42'),
       (NULL, 'LUNDI', '43'), (NULL, 'MARDI', '43'), (NULL, 'MERCREDI', '43'),
       (NULL, 'JEUDI', '43'), (NULL, 'VENDREDI', '43'), (NULL, 'SAMEDI', '43'),
       (NULL, 'LUNDI', '44'), (NULL, 'MARDI', '44'), (NULL, 'MERCREDI', '44'),
       (NULL, 'JEUDI', '44'), (NULL, 'VENDREDI', '44'), (NULL, 'SAMEDI', '44'),
       (NULL, 'LUNDI', '45'), (NULL, 'MARDI', '45'), (NULL, 'MERCREDI', '45'),
       (NULL, 'JEUDI', '45'), (NULL, 'VENDREDI', '45'), (NULL, 'SAMEDI', '45'),
       (NULL, 'LUNDI', '46'), (NULL, 'MARDI', '46'), (NULL, 'MERCREDI', '46'),
       (NULL, 'JEUDI', '46'), (NULL, 'VENDREDI', '46'), (NULL, 'SAMEDI', '46'),
       (NULL, 'LUNDI', '47'), (NULL, 'MARDI', '47'), (NULL, 'MERCREDI', '47'),
       (NULL, 'JEUDI', '47'), (NULL, 'VENDREDI', '47'), (NULL, 'SAMEDI', '47'),
       (NULL, 'LUNDI', '48'), (NULL, 'MARDI', '48'), (NULL, 'MERCREDI', '48'),
       (NULL, 'JEUDI', '48'), (NULL, 'VENDREDI', '48'), (NULL, 'SAMEDI', '48'),
       (NULL, 'LUNDI', '49'), (NULL, 'MARDI', '49'), (NULL, 'MERCREDI', '49'),
       (NULL, 'JEUDI', '49'), (NULL, 'VENDREDI', '49'), (NULL, 'SAMEDI', '49'),
       (NULL, 'LUNDI', '50'), (NULL, 'MARDI', '50'), (NULL, 'MERCREDI', '50'),
       (NULL, 'JEUDI', '50'), (NULL, 'VENDREDI', '50'), (NULL, 'SAMEDI', '50'),
       (NULL, 'LUNDI', '51'), (NULL, 'MARDI', '51'), (NULL, 'MERCREDI', '51'),
       (NULL, 'JEUDI', '51'), (NULL, 'VENDREDI', '51'), (NULL, 'SAMEDI', '51'),
       (NULL, 'LUNDI', '52'), (NULL, 'MARDI', '52'), (NULL, 'MERCREDI', '52'),
       (NULL, 'JEUDI', '52'), (NULL, 'VENDREDI', '52'), (NULL, 'SAMEDI', '52'),
       (NULL, 'LUNDI', '53'), (NULL, 'MARDI', '53'), (NULL, 'MERCREDI', '53'),
       (NULL, 'JEUDI', '53'), (NULL, 'VENDREDI', '53'), (NULL, 'SAMEDI', '53');


INSERT INTO `TRAVAILLE` (`ID_EMPLOYE`, `ID_HORAIRE`)
VALUES ('9', '1'), ('9', '2'), ('9', '3');